Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/manage.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/manage.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/DBUtils.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/DBUtils.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/Defaults.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/Defaults.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/DBUtils.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/DBUtils.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBService/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/Defaults.py changed, reloading.
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/Defaults.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /index/ProcessQueries/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 1765, in ProcessQueries
    res_data = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /index/ProcessQueries/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 1765, in ProcessQueries
    res_data = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /index/scaffoldPosLinkUI/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 999, in scaffoldPosLinkUI
    jsondata = massage_request_json(request)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 79, in massage_request_json
    jsondata = json.loads(body_unicode)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /index/ProcessQueries/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 1765, in ProcessQueries
    res_data = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /index/ProcessQueries/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 1765, in ProcessQueries
    res_data = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /index/ProcessQueries/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 1765, in ProcessQueries
    res_data = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Internal Server Error: /index/ProcessQueries/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 1765, in ProcessQueries
    res_data = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Method Not Allowed: /index/QueryByPrimaryAnnotation/
Not Found: /
Not Found: /favicon.ico
Not Found: /index/
Internal Server Error: /index/SetData_Usage_Policy/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/views.py", line 168, in SetData_Usage_Policy
    jsondata = json.loads(request.body.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Method Not Allowed: /index/SetData_Usage_Policy/
/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /index/UploadFile/
Traceback (most recent call last):
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/venv/lib/python3.5/site-packages/rest_framework/decorators.py", line 55, in handler
    return func(*args, **kwargs)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 347, in UploadFile
    records=GFFparse(gff_file)
  File "/home/azure/PycharmProjects/IICB_DJango/IICBsrvc/browserImage.py", line 202, in GFFparse
    seq_ids=gff_df['seq_id'].unique().tolist()[0]
IndexError: list index out of range
Watching for file changes with StatReloader
